# -*- coding: utf-8 -*-
"""04_clustering_mood.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgHWN0TNnalrBy1ynNj8j7Pp6h1hakXL

# 04 – Clustering & Mood / Style Discovery
**Project**: Spotify Music Recommender & Analysis  
**Author**: S33mi  
**Goal**: Discover natural groups in the audio feature space using unsupervised clustering.  
These clusters can later be interpreted as moods or styles and used for playlist generation.

## 1. Setup & Imports
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score, davies_bouldin_score
from sklearn.preprocessing import StandardScaler
import joblib
import requests #for url methods
from io import BytesIO #for url methods
import warnings

warnings.filterwarnings("ignore")
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (12, 6)
pd.set_option("display.max_columns", 40)

print("Libraries loaded successfully.")

"""## 2. Load Processed Data"""

# Run this File after running "02_feature_engineering.ipynb" Or use URL method
#final_df = pd.read_csv("data/processed/spotify_features_scaled.csv")
#X = np.load("data/processed/X_scaled.npy")
#feature_cols = joblib.load("models/feature_columns.pkl")

# -------------------------------------------------
# 1. Load the combined dataframe (CSV works with URL)
# -------------------------------------------------
url = "https://raw.githubusercontent.com/S33mi/spotify-music-recommender/main/data/processed/spotify_features_scaled.csv"
final_df = pd.read_csv(url)

# -------------------------------------------------
# 2. Load the pure feature matrix (.npy)
# -------------------------------------------------
url_npy = "https://raw.githubusercontent.com/S33mi/spotify-music-recommender/main/data/processed/X_scaled.npy"

response = requests.get(url_npy)
response.raise_for_status()          # raise error if download fails
X = np.load(BytesIO(response.content))

# -------------------------------------------------
# 3. Load feature column names (.pkl)
# -------------------------------------------------
url_feature_cols = "https://raw.githubusercontent.com/S33mi/spotify-music-recommender/main/data/models/feature_columns.pkl"

# feature columns
resp1 = requests.get(url_feature_cols)
resp1.raise_for_status()
feature_cols = joblib.load(BytesIO(resp1.content))



print(f"Data shape          : {final_df.shape}")
print(f"Feature matrix shape: {X.shape}")
print(f"Features            : {feature_cols}")

"""## 3. Determine Optimal Number of Clusters
We use the Elbow method and Silhouette score.
"""

# Use a sample for speed when testing many k values
sample_size = 15000
np.random.seed(42)
sample_idx = np.random.choice(len(X), size=sample_size, replace=False)
X_sample = X[sample_idx]

inertias = []
silhouettes = []
K_range = range(2, 16)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_sample)
    inertias.append(kmeans.inertia_)
    silhouettes.append(silhouette_score(X_sample, labels))

# Plot Elbow + Silhouette
fig, ax1 = plt.subplots(figsize=(12, 5))

ax1.plot(K_range, inertias, "o-", color="steelblue", label="Inertia (Elbow)")
ax1.set_xlabel("Number of clusters (k)")
ax1.set_ylabel("Inertia", color="steelblue")
ax1.tick_params(axis="y", labelcolor="steelblue")

ax2 = ax1.twinx()
ax2.plot(K_range, silhouettes, "s-", color="darkorange", label="Silhouette")
ax2.set_ylabel("Silhouette Score", color="darkorange")
ax2.tick_params(axis="y", labelcolor="darkorange")

plt.title("Elbow Method + Silhouette Score")
fig.tight_layout()
plt.show()

print("Silhouette scores:")
for k, s in zip(K_range, silhouettes):
    print(f"k={k:2d} → {s:.4f}")

"""**Choose k** based on the plots.  
A good practical range for this dataset is usually **k = 6 to 10**.  
We will proceed with **k = 8** (you can change it).
"""

OPTIMAL_K = 8

"""## 4. Fit Final K-Means on Full Data"""

kmeans = KMeans(
    n_clusters=OPTIMAL_K,
    random_state=42,
    n_init=20,
    max_iter=500
)

cluster_labels = kmeans.fit_predict(X)
final_df["cluster"] = cluster_labels

print("Cluster distribution:")
print(final_df["cluster"].value_counts().sort_index())

"""### Cluster Quality Metrics"""

sil = silhouette_score(X, cluster_labels, sample_size=20000, random_state=42)
db = davies_bouldin_score(X, cluster_labels)

print(f"Silhouette Score     : {sil:.4f}")
print(f"Davies-Bouldin Index : {db:.4f}  (lower is better)")

"""## 5. Visualize Clusters with PCA"""

pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X)

pca_df = pd.DataFrame({
    "PC1": X_pca[:, 0],
    "PC2": X_pca[:, 1],
    "cluster": cluster_labels
})

plt.figure(figsize=(12, 8))
sns.scatterplot(
    data=pca_df.sample(8000, random_state=42),
    x="PC1", y="PC2",
    hue="cluster",
    palette="tab10",
    alpha=0.6,
    s=20
)
plt.title(f"K-Means Clusters (k={OPTIMAL_K}) – PCA Projection")
plt.legend(title="Cluster", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

print(f"PCA explained variance (2 components): {pca.explained_variance_ratio_.sum():.3f}")

"""## 6. Interpret Clusters – Feature Profiles"""

# Average feature values per cluster (on original scaled features)
cluster_profile = final_df.groupby("cluster")[feature_cols].mean()

# Also add size and average popularity
cluster_profile["size"] = final_df.groupby("cluster").size()
cluster_profile["avg_popularity"] = final_df.groupby("cluster")["popularity"].mean()

display(cluster_profile.round(3))

"""### Heatmap of Cluster Centroids"""

plt.figure(figsize=(12, 6))
sns.heatmap(
    cluster_profile[feature_cols],
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0
)
plt.title("Cluster Centroids (StandardScaled Features)")
plt.tight_layout()
plt.show()

"""## 7. Assign Mood / Style Labels (Manual Interpretation)
Look at the centroid heatmap and give each cluster a human-readable name.
"""

# Example labels – UPDATE THESE after looking at the heatmap!
mood_labels = {
    0: "High Energy Dance",
    1: "Acoustic / Chill",
    2: "Dark / Intense",
    3: "Happy Pop",
    4: "Instrumental / Ambient",
    5: "Upbeat Electronic",
    6: "Melancholic / Low Valence",
    7: "Live / Raw Energy"
}

# Make sure the dictionary covers all clusters
final_df["mood"] = final_df["cluster"].map(mood_labels)

print("Mood distribution:")
print(final_df["mood"].value_counts())

"""### Top Genres inside each Mood"""

for mood in sorted(final_df["mood"].dropna().unique()):
    print(f"\n=== {mood} ===")
    top_genres = (
        final_df[final_df["mood"] == mood]["track_genre"]
        .value_counts()
        .head(6)
    )
    print(top_genres)

"""## 8. Example: Create a Mood Playlist"""

def get_mood_playlist(mood_name: str, n: int = 15, min_popularity: int = 30):
    """
    Return a sample of tracks from a given mood cluster.
    """
    subset = final_df[
        (final_df["mood"] == mood_name) &
        (final_df["popularity"] >= min_popularity)
    ]

    if subset.empty:
        print(f"No tracks found for mood: {mood_name}")
        return None

    playlist = subset.sample(n=min(n, len(subset)), random_state=42)[
        ["track_name", "artists", "track_genre", "popularity", "cluster"]
    ]
    return playlist.sort_values("popularity", ascending=False).reset_index(drop=True)

# Example
print("Example playlist – High Energy Dance:")
display(get_mood_playlist("High Energy Dance", n=12))

print("\nExample playlist – Acoustic / Chill:")
display(get_mood_playlist("Acoustic / Chill", n=12))

"""## 9. Optional: Hierarchical Clustering (on a sample)"""

# Hierarchical clustering is slower, so we use a smaller sample
hier_sample_size = 3000
hier_idx = np.random.choice(len(X), size=hier_sample_size, replace=False)
X_hier = X[hier_idx]

hierarchical = AgglomerativeClustering(n_clusters=OPTIMAL_K, linkage="ward")
hier_labels = hierarchical.fit_predict(X_hier)

print("Hierarchical clustering finished on sample.")
print(pd.Series(hier_labels).value_counts().sort_index())

"""## 10. Save Clustering Artifacts


"""

# %%
import os
os.makedirs("models", exist_ok=True)
os.makedirs("data/processed", exist_ok=True)

# Save the fitted KMeans model
joblib.dump(kmeans, "models/kmeans_mood.pkl")

# Save the dataframe with cluster + mood labels
final_df.to_csv("data/processed/spotify_with_clusters.csv", index=False)

# Save mood mapping
joblib.dump(mood_labels, "models/mood_labels.pkl")

print("Saved:")
print("  - models/kmeans_mood.pkl")
print("  - data/processed/spotify_with_clusters.csv")
print("  - models/mood_labels.pkl")

"""## 11. Summary & Insights

- Chose **k = 8** clusters based on Elbow + Silhouette analysis.
- Visualized clusters with PCA.
- Created interpretable **mood / style labels**.
- Generated example mood-based playlists.
- Saved the model and labeled data for future use (playlist optimization, demo app, etc.).

**Possible next steps**:
- Improve mood labels after deeper inspection of centroids and top tracks.
- Build a simple Gradio/Streamlit demo that recommends songs + shows mood.
- Move to **Playlist Optimization** project (use clusters + audio features as input).
"""