# -*- coding: utf-8 -*-
"""01_data_collection_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YxRZ5awgzh3TyLNSmpYwas3rQhsmkJMr

# 01 – Data Collection & Exploratory Data Analysis
**Project**: Spotify Music Recommender & Analysis  
**Author**: S33mi  
**Goal**: Load the Spotify tracks dataset, clean it, and perform thorough EDA to understand audio features, genres, and popularity patterns.  
Insights from this notebook will guide feature engineering and the recommender system.

## 1. Setup & Imports
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (12, 6)
pd.set_option("display.max_columns", 50)

print("Libraries loaded successfully.")

"""## 2. Load the Dataset

Download the dataset from:  
https://www.kaggle.com/datasets/maharshipandya/-spotify-tracks-dataset  
Place `dataset.csv` in a `data/` folder (or update the path below).
OR you can use kagglehub
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("maharshipandya/-spotify-tracks-dataset")

print("Path to dataset files:", path)

# Update the path if needed
#DATA_PATH = "data/dataset.csv"

#df = pd.read_csv(DATA_PATH)
#print(f"Dataset shape: {df.shape}")
#df.head()
# --------------------
#path = kagglehub.dataset_download("maharshipandya/-spotify-tracks-dataset")
df = pd.read_csv(f"{path}/dataset.csv")   # ← change filename if different
print(f"Dataset shape: {df.shape}")
df.head()

"""
## 3. Basic Information & Data Quality
"""

print("=== Dataset Info ===")
df.info()

print("\n=== Missing Values ===")
missing = df.isnull().sum()
print(missing[missing > 0])

print("\n=== Duplicate Rows ===")
print(f"Number of duplicate rows: {df.duplicated().sum()}")

print("\n=== Unique Values (selected columns) ===")
print(f"Unique track_ids : {df['track_id'].nunique()}")
print(f"Unique artists   : {df['artists'].nunique()}")
print(f"Unique genres    : {df['track_genre'].nunique()}")

"""
### Quick Cleaning
- Drop exact duplicates
- Remove rows with missing critical values (if any)
- Convert duration to minutes for readability
"""

# Drop duplicates
df = df.drop_duplicates(subset=["track_id"]).reset_index(drop=True)

# Duration in minutes
df["duration_min"] = df["duration_ms"] / 60000

# Optional: drop the original Unnamed index column if present
if "Unnamed: 0" in df.columns:
    df = df.drop(columns=["Unnamed: 0"])

print(f"Shape after cleaning: {df.shape}")

"""## 4. Audio Feature Descriptions

These are the core features we will use for recommendation:

| Feature            | Description                                      | Range      |
|--------------------|--------------------------------------------------|------------|
| danceability       | How suitable a track is for dancing              | 0.0 – 1.0  |
| energy             | Intensity and activity                           | 0.0 – 1.0  |
| key                | Musical key (0 = C, 1 = C♯/D♭, …)                | 0 – 11     |
| loudness           | Overall loudness in dB                           | typically -60 to 0 |
| mode               | Major (1) or Minor (0)                           | 0 or 1     |
| speechiness        | Presence of spoken words                         | 0.0 – 1.0  |
| acousticness       | Confidence the track is acoustic                 | 0.0 – 1.0  |
| instrumentalness   | Predicts whether a track contains no vocals      | 0.0 – 1.0  |
| liveness           | Presence of an audience                          | 0.0 – 1.0  |
| valence            | Musical positiveness (happy → sad)               | 0.0 – 1.0  |
| tempo              | Estimated tempo in BPM                           | usually 50–200 |
| duration_ms        | Track length in milliseconds                     | –          |
| popularity         | Spotify popularity score                         | 0 – 100    |

## 5. Univariate Analysis – Distributions of Audio Features
"""

audio_features = [
    "danceability", "energy", "loudness", "speechiness",
    "acousticness", "instrumentalness", "liveness",
    "valence", "tempo", "duration_min", "popularity"
]

fig, axes = plt.subplots(3, 4, figsize=(18, 12))
axes = axes.flatten()

for i, col in enumerate(audio_features):
    sns.histplot(df[col], kde=True, ax=axes[i], color="steelblue", bins=40)
    axes[i].set_title(col, fontsize=12)
    axes[i].set_xlabel("")

# Hide unused subplot
if len(audio_features) < len(axes):
    axes[-1].set_visible(False)

plt.tight_layout()
plt.suptitle("Distribution of Key Audio Features", y=1.02, fontsize=16)
plt.show()

"""
## 6. Correlation Analysis"""

corr_matrix = df[audio_features].corr()

plt.figure(figsize=(12, 9))
sns.heatmap(
    corr_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    square=True,
    linewidths=0.5
)
plt.title("Correlation Heatmap of Audio Features", fontsize=14)
plt.tight_layout()
plt.show()

"""**Quick observations** (update after running):
- Energy and loudness are usually strongly positively correlated.
- Acousticness tends to be negatively correlated with energy and loudness.
- Valence (positiveness) often shows moderate positive correlation with danceability.

# ## 7. Genre Analysis
"""

# Top 15 genres by number of tracks
top_genres = df["track_genre"].value_counts().head(15)

plt.figure(figsize=(12, 6))
sns.barplot(x=top_genres.values, y=top_genres.index, palette="viridis")
plt.title("Top 15 Genres by Number of Tracks")
plt.xlabel("Number of Tracks")
plt.ylabel("Genre")
plt.tight_layout()
plt.show()

# Average popularity by genre (top 15)
genre_popularity = (
    df.groupby("track_genre")["popularity"]
    .mean()
    .sort_values(ascending=False)
    .head(15)
)

plt.figure(figsize=(12, 6))
sns.barplot(x=genre_popularity.values, y=genre_popularity.index, palette="magma")
plt.title("Top 15 Genres by Average Popularity")
plt.xlabel("Average Popularity")
plt.ylabel("Genre")
plt.tight_layout()
plt.show()

"""## 8. Popularity Insights

"""

plt.figure(figsize=(10, 5))
sns.histplot(df["popularity"], bins=50, kde=True, color="teal")
plt.title("Distribution of Track Popularity")
plt.xlabel("Popularity (0–100)")
plt.show()

# High popularity tracks
print("Top 10 most popular tracks:")
display(
    df.nlargest(10, "popularity")[
        ["track_name", "artists", "track_genre", "popularity", "danceability", "energy", "valence"]
    ]
)

"""
## 9. Feature Relationships with Popularity"""

# Scatter plots of selected features vs popularity
selected = ["danceability", "energy", "valence", "acousticness", "tempo"]

fig, axes = plt.subplots(2, 3, figsize=(16, 9))
axes = axes.flatten()

for i, col in enumerate(selected):
    sns.scatterplot(
        data=df.sample(5000, random_state=42),  # sample for speed
        x=col,
        y="popularity",
        alpha=0.3,
        ax=axes[i],
        color="steelblue"
    )
    axes[i].set_title(f"{col} vs Popularity")

axes[-1].set_visible(False)
plt.tight_layout()
plt.show()

"""## 10. Summary of Key Insights
  
 - Dataset size after cleaning: **(89741, 21)** tracks
 - Most common genres: **k-pop**
 - Features with strongest correlation to popularity: **danceability and loudness**
 - Notable patterns (e.g., high-energy tracks, valence distribution, etc.):
    - Energy and loudness are usually strongly positively correlated
    - Acousticness tends to be negatively correlated with energy and loudness.
    - Valence (positiveness) often shows moderate positive correlation with danceability.
    - Most of avaiable tracks are very unpopuler or have a low play count.

 These insights will guide:
 - Feature selection for the recommender
 - Scaling strategy
 - Clustering approach in later notebooks

## Next Steps

→ `02_feature_engineering.ipynb`  
- Scale numerical features  
- Optional encoding of key / mode / genre  
- Create a clean feature matrix for similarity calculations
"""