# -*- coding: utf-8 -*-
"""02_feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GYTZEx4UHpNSXQmVwmBm7qOh4ahhZiQZ

# 02 – Feature Engineering
**Project**: Spotify Music Recommender & Analysis  
**Author**: S33mi  
**Goal**: Prepare a clean, scaled feature matrix ready for content-based recommendation and clustering.

This notebook builds directly on the cleaned data from `01_data_collection_eda.ipynb`.

## 1. Setup & Imports
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.decomposition import PCA
import joblib
import warnings
import kagglehub #for dataset

warnings.filterwarnings("ignore")
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (12, 6)
pd.set_option("display.max_columns", 50)

print("Libraries loaded successfully.")

"""## 2. Load Cleaned Data

Make sure you have already run notebook 01 and saved the cleaned dataset  
(or simply re-load and apply the same cleaning steps).

"""

#DATA_PATH = "data/dataset.csv"          # original file
# If you saved a cleaned version in notebook 01, use that path instead:
# DATA_PATH = "data/cleaned_spotify.csv"

#df = pd.read_csv(DATA_PATH)
#----------------------------

path = kagglehub.dataset_download("maharshipandya/-spotify-tracks-dataset")
df = pd.read_csv(f"{path}/dataset.csv")   # ← change filename if different


# ---------- Same cleaning steps as notebook 01 ----------
df = df.drop_duplicates(subset=["track_id"]).reset_index(drop=True)

if "Unnamed: 0" in df.columns:
    df = df.drop(columns=["Unnamed: 0"])

df["duration_min"] = df["duration_ms"] / 60000

print(f"Loaded data shape: {df.shape}")
df.head()

"""## 3. Select Features for the Recommender

We focus on the core audio features that describe the *sound* of a track.  
These will form the basis of content-based similarity.
"""

# Core numerical features for silarity
feature_cols = [
    "danceability",
    "energy",
    "loudness",
    "speechiness",
    "acousticness",
    "instrumentalness",
    "liveness",
    "valence",
    "tempo",
    "duration_min"          # using minutes instead of ms
]

# Optional: include popularity if you want it in the feature space
# feature_cols.append("popularity")

# Keep metadata for later (recommendations, display, etc.)
meta_cols = [
    "track_id",
    "track_name",
    "artists",
    "album_name",
    "track_genre",
    "popularity"
]

# Create working dataframes
features_df = df[feature_cols].copy()
meta_df = df[meta_cols].copy()

print("Selected feature columns:")
print(feature_cols)
print(f"\nFeature matrix shape: {features_df.shape}")

"""### Quick check for missing values in features

"""

print("Missing values in feature columns:")
print(features_df.isnull().sum())

# If any missing values exist, fill with median (rare in this dataset)
features_df = features_df.fillna(features_df.median())

"""
## 4. Feature Scaling

Audio features have different scales (e.g. loudness is in dB, tempo in BPM, others 0-1).  
We need to scale them before computing distances / similarity.
"""

# We will try two common scalers and keep the StandardScaler version as primary

scaler_standard = StandardScaler()
scaler_minmax = MinMaxScaler()

features_scaled_std = scaler_standard.fit_transform(features_df)
features_scaled_mm = scaler_minmax.fit_transform(features_df)

# Convert back to DataFrames for convenience
features_std_df = pd.DataFrame(features_scaled_std, columns=feature_cols)
features_mm_df = pd.DataFrame(features_scaled_mm, columns=feature_cols)

print("StandardScaler – mean & std of scaled features:")
print(features_std_df.agg(["mean", "std"]).round(4))

"""### Visual comparison of scaling"""

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

sns.boxplot(data=features_std_df, ax=axes[0], orient="h", palette="Blues")
axes[0].set_title("After StandardScaler")

sns.boxplot(data=features_mm_df, ax=axes[1], orient="h", palette="Greens")
axes[1].set_title("After MinMaxScaler")

plt.tight_layout()
plt.show()

"""**Decision**: We will use **StandardScaler** as the primary scaling method  
(better for distance-based methods like cosine similarity and KNN when features are roughly Gaussian).

## 5. Optional: Dimensionality Reduction Preview (PCA)
"""

pca = PCA(n_components=0.95, random_state=42)   # keep 95% variance
pca_features = pca.fit_transform(features_scaled_std)

print(f"Original features : {features_scaled_std.shape[1]}")
print(f"PCA components    : {pca_features.shape[1]}")
print(f"Explained variance: {pca.explained_variance_ratio_.sum():.3f}")

# Cumulative variance plot
plt.figure(figsize=(10, 5))
plt.plot(np.cumsum(pca.explained_variance_ratio_), marker="o")
plt.axhline(0.95, color="red", linestyle="--", label="95% variance")
plt.xlabel("Number of Components")
plt.ylabel("Cumulative Explained Variance")
plt.title("PCA – Cumulative Explained Variance")
plt.legend()
plt.grid(True)
plt.show()

"""PCA is useful for visualization and can be used later if we want a lower-dimensional representation.  
For the main recommender we will keep the full scaled feature set.

## 6. Create Final Feature Matrix + Metadata
"""

# Final scaled feature matrix (StandardScaler)
X = features_std_df.copy()

# Combine with metadata for easy lookup later
final_df = pd.concat([meta_df.reset_index(drop=True), X], axis=1)

print("Final combined dataframe shape:", final_df.shape)
final_df.head()

"""
## 7. Save Artifacts for Next Notebooks
"""

import os
os.makedirs("data/processed", exist_ok=True)
os.makedirs("models", exist_ok=True)

# Save the scaled feature matrix + metadata
final_df.to_csv("data/processed/spotify_features_scaled.csv", index=False)

# Save only the pure feature matrix (numpy) for fast loading in recommender
np.save("data/processed/X_scaled.npy", X.values)

# Save the scaler so we can transform new songs later
joblib.dump(scaler_standard, "models/standard_scaler.pkl")

# Save the list of feature columns
joblib.dump(feature_cols, "models/feature_columns.pkl")

print("Artifacts saved:")
print("  - data/processed/spotify_features_scaled.csv")
print("  - data/processed/X_scaled.npy")
print("  - models/standard_scaler.pkl")
print("  - models/feature_columns.pkl")

"""## 8. Quick Sanity Check"""

print("Feature matrix statistics (after StandardScaler):")
display(X.describe().round(3))

print("\nSample of final dataframe:")
display(final_df[["track_name", "artists", "track_genre", "popularity"] + feature_cols].head())

"""
## Summary

- Selected 10 core audio features  
- Applied **StandardScaler**  
- Optional PCA analysis performed  
- Saved:
  - Scaled feature matrix + metadata
  - Pure numpy feature matrix
  - Fitted scaler & feature column list

**Next notebook**: `03_recommender.ipynb`  
→ Build content-based recommender using cosine similarity / KNN on the scaled features."""