# -*- coding: utf-8 -*-
"""03_recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1brr6HGZJFHO472ups8p_gFtoed89ryvR

# 03 – Content-Based Music Recommender
**Project**: Spotify Music Recommender & Analysis  
**Author**: S33mi  
**Goal**: Build a practical content-based recommender using the scaled audio features prepared in notebook 02.

We implement two approaches:
1. **Cosine Similarity** (classic, good for understanding)
2. **Nearest Neighbors (KNN)** – more scalable and recommended for the full dataset

## 1. Setup & Imports
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors
import joblib
import requests #for url methods
from io import BytesIO #for url methods
import warnings

warnings.filterwarnings("ignore")
sns.set_style("whitegrid")
pd.set_option("display.max_colwidth", 100)
pd.set_option("display.max_columns", 30)

print("Libraries loaded successfully.")

"""## 2. Load Processed Data from Notebook 02"""

# Load the combined dataframe (metadata + scaled features)
#final_df = pd.read_csv("data/processed/spotify_features_scaled.csv")

# Load pure feature matrix
#X = np.load("data/processed/X_scaled.npy")

# Load feature column names and scaler (useful later)
#feature_cols = joblib.load("models/feature_columns.pkl")
#scaler = joblib.load("models/standard_scaler.pkl")

#print(f"Data shape          : {final_df.shape}")
#print(f"Feature matrix shape: {X.shape}")
#print(f"Feature columns     : {feature_cols}")

# Quick look
#final_df[["track_name", "artists", "track_genre", "popularity"] + feature_cols].head()
#--------------------OR USE URL  METHOD-----------------------------------------


# -------------------------------------------------
# 1. Load the combined dataframe (CSV works with URL)
# -------------------------------------------------
url = "https://raw.githubusercontent.com/S33mi/spotify-music-recommender/main/data/processed/spotify_features_scaled.csv"
final_df = pd.read_csv(url)

# -------------------------------------------------
# 2. Load the pure feature matrix (.npy)
# -------------------------------------------------
url_npy = "https://raw.githubusercontent.com/S33mi/spotify-music-recommender/main/data/processed/X_scaled.npy"

response = requests.get(url_npy)
response.raise_for_status()          # raise error if download fails
X = np.load(BytesIO(response.content))

# -------------------------------------------------
# 3. Load feature column names and scaler (.pkl)
# -------------------------------------------------
url_feature_cols = "https://raw.githubusercontent.com/S33mi/spotify-music-recommender/main/data/models/feature_columns.pkl"
url_scaler      = "https://raw.githubusercontent.com/S33mi/spotify-music-recommender/main/data/models/standard_scaler.pkl"

# feature columns
resp1 = requests.get(url_feature_cols)
resp1.raise_for_status()
feature_cols = joblib.load(BytesIO(resp1.content))

# scaler
resp2 = requests.get(url_scaler)
resp2.raise_for_status()
scaler = joblib.load(BytesIO(resp2.content))

# -------------------------------------------------
# Quick checks
# -------------------------------------------------
print(f"Data shape          : {final_df.shape}")
print(f"Feature matrix shape: {X.shape}")
print(f"Feature columns     : {feature_cols}")

# Preview
final_df[["track_name", "artists", "track_genre", "popularity"] + feature_cols].head()

"""## 3. Helper: Search for a Track
Useful because many tracks can share similar names.
"""

def search_track(query: str, top_n: int = 10):
    """
    Simple case-insensitive search on track_name and artists.
    Returns a small dataframe of matching tracks.
    """
    query = query.lower()
    mask = (
        final_df["track_name"].str.lower().str.contains(query, na=False) |
        final_df["artists"].str.lower().str.contains(query, na=False)
    )
    results = final_df.loc[mask, ["track_id", "track_name", "artists", "track_genre", "popularity"]]
    return results.head(top_n)

# Example
print("Search example – 'blinding':")
display(search_track("blinding"))

"""## 4. Approach A – Cosine Similarity (Full Matrix)

**Note**: Building a full N×N similarity matrix for ~90–100k tracks is memory-heavy.  
We demonstrate it on a **sample** first, then move to the scalable KNN version.
"""

# Take a manageable sample for demonstration
sample_size = 8000
sample_idx = np.random.choice(len(final_df), size=sample_size, replace=False)
sample_df = final_df.iloc[sample_idx].reset_index(drop=True)
X_sample = X[sample_idx]

print(f"Working with sample of {sample_size} tracks for full cosine matrix demo.")

# Compute cosine similarity matrix
cosine_sim = cosine_similarity(X_sample)
print(f"Cosine similarity matrix shape: {cosine_sim.shape}")

def recommend_cosine(track_name: str, top_n: int = 10, sample_df=sample_df, sim_matrix=cosine_sim):
    """
    Recommend songs using pre-computed cosine similarity (sample version).
    """
    # Find the track (take first match)
    matches = sample_df[sample_df["track_name"].str.lower() == track_name.lower()]
    if matches.empty:
        # fallback to partial match
        matches = sample_df[sample_df["track_name"].str.lower().str.contains(track_name.lower(), na=False)]

    if matches.empty:
        print(f"Track '{track_name}' not found in the sample.")
        return None

    idx = matches.index[0]
    sim_scores = list(enumerate(sim_matrix[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Exclude the track itself
    sim_scores = sim_scores[1:top_n+1]
    track_indices = [i[0] for i in sim_scores]

    recommendations = sample_df.iloc[track_indices][
        ["track_name", "artists", "track_genre", "popularity"]
    ].copy()
    recommendations["similarity"] = [i[1] for i in sim_scores]

    return recommendations.reset_index(drop=True)

"""### Test Cosine Recommender (on sample)"""

# Pick a track that exists in the sample (you can change this)
example_track = sample_df.iloc[2]["track_name"] # change the index number
print(f"Seed track: {example_track}")
print(f"Artist    : {sample_df.iloc[2]['artists']}")
print(f"Genre     : {sample_df.iloc[2]['track_genre']}\n")

recs = recommend_cosine(example_track, top_n=8)
display(recs)

"""## 5. Approach B – Nearest Neighbors (Recommended – Scalable)"""

# Fit NearestNeighbors on the FULL scaled feature matrix
# Using cosine distance (equivalent to 1 - cosine similarity)
knn = NearestNeighbors(
    n_neighbors=15,          # we will request top 10 + some buffer
    metric="cosine",
    algorithm="brute",       # exact, works well for this size
    n_jobs=-1
)

knn.fit(X)
print("NearestNeighbors model fitted on full dataset.")

def recommend_knn(
    track_name: str = None,
    track_id: str = None,
    top_n: int = 10,
    return_distance: bool = True
):
    """
    Recommend similar tracks using KNN (cosine distance).

    Provide either track_name or track_id.
    """
    if track_id is not None:
        matches = final_df[final_df["track_id"] == track_id]
    elif track_name is not None:
        matches = final_df[final_df["track_name"].str.lower() == track_name.lower()]
        if matches.empty:
            matches = final_df[final_df["track_name"].str.lower().str.contains(track_name.lower(), na=False)]
    else:
        raise ValueError("Please provide either track_name or track_id.")

    if matches.empty:
        print("Track not found.")
        return None

    # Take the first match
    seed = matches.iloc[0]
    seed_idx = matches.index[0]

    print(f"Seed Track : {seed['track_name']}")
    print(f"Artists    : {seed['artists']}")
    print(f"Genre      : {seed['track_genre']}")
    print(f"Popularity : {seed['popularity']}\n")

    # Get neighbors
    distances, indices = knn.kneighbors(
        X[seed_idx].reshape(1, -1),
        n_neighbors=top_n + 1
    )

    # Remove the seed itself (distance ~0)
    neighbor_indices = indices[0][1:]
    neighbor_distances = distances[0][1:]

    recs = final_df.iloc[neighbor_indices][
        ["track_id", "track_name", "artists", "track_genre", "popularity"]
    ].copy()

    if return_distance:
        # Convert cosine distance to similarity for easier reading
        recs["cosine_similarity"] = 1 - neighbor_distances

    return recs.reset_index(drop=True)

"""### Test KNN Recommender"""

# Example 1 – search first, then recommend
# Sample -> "Comedy", "Sevmekten Kim Usanır", "Blinding Lights", "Atrakce", "Rain", "Lo-fi", "The Steeple","The Resistance"
search_results = search_track("Lo-fi", top_n=5)
display(search_results)

# Use one of the track_ids or names from the search
if not search_results.empty:
    example_id = search_results.iloc[0]["track_id"]
    recs_knn = recommend_knn(track_id=example_id, top_n=10)
    display(recs_knn)
else:
    # Fallback – pick any popular track
    popular = final_df.nlargest(1, "popularity")
    recs_knn = recommend_knn(track_id=popular.iloc[0]["track_id"], top_n=10)
    display(recs_knn)

# Another example – by name
recs2 = recommend_knn(track_name="Shape of You", top_n=8)
display(recs2)

"""## 6. Recommend from a Custom Feature Vector
Useful later if you want to feed a new song’s audio features.
"""

def recommend_from_features(feature_vector, top_n: int = 10):
    """
    feature_vector: 1D array-like of length = len(feature_cols)
                    (already scaled with the same StandardScaler)
    """
    feature_vector = np.array(feature_vector).reshape(1, -1)

    distances, indices = knn.kneighbors(feature_vector, n_neighbors=top_n)

    recs = final_df.iloc[indices[0]][
        ["track_name", "artists", "track_genre", "popularity"]
    ].copy()
    recs["cosine_similarity"] = 1 - distances[0]

    return recs.reset_index(drop=True)

# Example: take an existing track’s features and get neighbors (should return itself first)
example_features = X[100]
recs_custom = recommend_from_features(example_features, top_n=6)

display(recs_custom)

"""## 7. Save the Recommender Artifacts"""

import os
os.makedirs("models", exist_ok=True)

# Save the fitted KNN model
joblib.dump(knn, "models/knn_recommender.pkl")

# Also save a lightweight version of the metadata for easy lookup
meta_for_rec = final_df[["track_id", "track_name", "artists", "track_genre", "popularity"]].copy()
meta_for_rec.to_csv("data/processed/meta_for_recommender.csv", index=False)

print("Saved:")
print("  - models/knn_recommender.pkl")
print("  - data/processed/meta_for_recommender.csv")

"""## 8. Quick Evaluation Ideas (Manual)

Content-based recommenders are usually evaluated qualitatively or with:
- Genre consistency of recommendations
- Diversity (how different the top-N are)
- User studies / listening tests

You can also compute average genre match rate for a sample of seeds.


"""

def genre_match_rate(seed_genre, recommendations):
    if recommendations is None or recommendations.empty:
        return 0.0
    matches = (recommendations["track_genre"] == seed_genre).sum()
    return matches / len(recommendations)

# Example check
seed_genre = final_df.iloc[0]["track_genre"]
recs_check = recommend_knn(track_id=final_df.iloc[0]["track_id"], top_n=10)
print(f"Seed genre: {seed_genre}")
print(f"Genre match rate in top-10: {genre_match_rate(seed_genre, recs_check):.2%}")

"""## Summary

- Built a **scalable KNN-based content recommender** using cosine distance on StandardScaled audio features.
- Provided helper functions for search + recommendation by name or track_id.
- Saved the model and metadata for use in a future demo (Gradio / Streamlit) or the playlist optimization project.

**Next notebook**: `04_clustering_mood.ipynb`  
→ Discover natural groups / mood playlists with K-Means (and optionally hierarchical clustering).
"""